### PR TITLE
Provide a match-like interface for destructuring the data

### PR DESCRIPTION
**Pull request by lakinwecker**
Based on this blog post: https://blog.parametricstudios.com/posts/pattern-matching-custom-data-types/  I added a match like interface that can be used instead of fold.  

I'm not 100% happy with the resulting code, I've repeated things too often, but this compiles with typescript and the new tests pass.  If you like the idea of adding it, then I can do some more work to clean it up and try and make it more simple to use.

### CODE REVIEW

**Comment by lakinwecker** [comment]
FWIW, the travis build is erroring the same way my local build errors even without my changes. Unsure what's going on here.

**Comment by lakinwecker** [comment]
This PR is pretty busted if you try and use it in a non-testing environment. I have a working copy locally that provides a free function which works similar to fold, but allows you to specify a default. I'll try and find some time to update this PR when I get a chance.

**Comment by abraham** [comment]
It's been a while. If this is something you're still interested in please reopen.

**Comment by lakinwecker** [comment]
We ended up making our own remote data with a match, so not necessary here anymore. Hope all is well. :D

**Pull request closed without merging**
